In [5]:
import numpy as np 
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
# addtion
print(a+b)
#subtraction
print(a-b)
#multiplication
print(a*b)
#division
print(a/b)
#dot
print(a.dot(b))
s=4
print("Result = ",a*s)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
70
Result =  [ 4  8 12 16]


In [6]:
a1=np.array([[10,20],[30,40]])
b1=np.array([[3,7],[5,9]])
print(a1%b1)
print(np.cross(a1,b1))

[[1 6]
 [0 4]]
[10 70]


In [11]:
import numpy as np
def my_func(x,y):
    if x>y:
        return x-y
    else:
        return x+y
    

In [13]:
arr1=[10,7,2]
arr2=[6,5,3]
v=np.vectorize(my_func)
print("Result=",v(arr1,arr2))

Result= [4 2 5]
