In [7]:
import numpy as np
a=np.array([10,20,30])
print("One Dimensional array:\n",a)

import numpy as np
b=np.array([[10,30,60],[8,60,70]])
print("Two dimensional array:\n",b)


One Dimensional array:
 [10 20 30]
Two dimensional array:
 [[10 30 60]
 [ 8 60 70]]


In [1]:
import numpy as np
w=np.zeros((3,4))
print(w)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [2]:
import numpy as np
o=np.random.random((3,2))
print(o)

[[0.27782848 0.11635632]
 [0.75099193 0.75585418]
 [0.50000859 0.50433497]]


In [3]:
import numpy as np
p=np.arange(1,10,1)
print(p)


[1 2 3 4 5 6 7 8 9]


In [4]:
import numpy as np
p=np.arange(1,10,2)
print(p)

[1 3 5 7 9]


In [5]:
import numpy as np
p=np.arange(0,10,2)
print(p)


[0 2 4 6 8]


In [6]:
import numpy as np
a=np.array([[5,6,7,3],[3,5,8,0],[7,9,0,1]])
n=a.reshape((4,3))
print("original array:\n",a)
print("reshaped array:\n",n)


original array:
 [[5 6 7 3]
 [3 5 8 0]
 [7 9 0 1]]
reshaped array:
 [[5 6 7]
 [3 3 5]
 [8 0 7]
 [9 0 1]]


In [8]:
import numpy as np
e=np.zeros((5,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np
p=np.arange(1,100,5)
print(p)


[ 1  6 11 16 21 26 31 36 41 46 51 56 61 66 71 76 81 86 91 96]


In [18]:
d=np.random.random((5,3))
print(d)

[[0.56382271 0.28052182 0.47237859]
 [0.79363063 0.49294594 0.0893758 ]
 [0.45117195 0.80179612 0.06899232]
 [0.32967748 0.43054395 0.90348006]
 [0.3762655  0.51130286 0.87268318]]


In [19]:
g=d.reshape((3,5))
print(g)

[[0.56382271 0.28052182 0.47237859 0.79363063 0.49294594]
 [0.0893758  0.45117195 0.80179612 0.06899232 0.32967748]
 [0.43054395 0.90348006 0.3762655  0.51130286 0.87268318]]


In [26]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [34]:
g=arr.flatten()
print(g)

[1 2 3 4 5 6 7 8 9]


In [31]:
g=arr.flatten()
print(g)

[ 1  2  3  4  5  6  7  8  9 11 12 13]


In [38]:
f=arr.ndim
print("Number of dimensions:",f)

Number of dimensions: 2


In [5]:
print("\n shape of an array:",arr.shape)


 shape of an array: (3, 3)


In [15]:
print(arr.dtype)

int32


In [14]:
arrf=arr.astype('f')
print(arrf)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [13]:
print(arrf.dtype)

float32


In [27]:
print(arr.size)

9
