In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:6])

[3 4 5 6]


In [2]:
print(arr[1:7:2])

[2 4 6]


In [7]:
print(arr[::-1])

[9 8 7 6 5 4 3 2 1]


In [9]:
import numpy as np
arr2=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr2)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [20]:
print(arr2[0:3,0:3])

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [23]:
print(arr2[0:3,1:3])

[[20 30]
 [50 60]
 [80 90]]


In [33]:
print(arr2[:,0])

[10 40 70]


In [36]:
print(arr2[1,:])

[40 50 60]


In [40]:
print(arr2[0,0],arr2[1,2])

10 60


In [42]:
print(arr[4])

5


In [45]:
print(arr[-1])

9


In [46]:
print(arr[1:4])

[2 3 4]


In [52]:
print(arr[arr>6])

[7 8 9]


In [55]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
h=np.hstack((a1,a2))
print(h)

[[1 2 5 6]
 [3 4 7 8]]


In [56]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
h=np.vstack((a1,a2))
print(h)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
combines data level into new depth level.rows to column

In [57]:
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
h=np.dstack((a1,a2))
print(h)

[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]


In [62]:
b=np.split(arr,3)
print(b)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [63]:
print(np.array_split(arr,4))

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
